name: .NET Build & Publish EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: build specific project (skip xaml junk)
      run: dotnet build BluetoothLEExplorer/BluetoothLEExplorer/VirtualBT.csproj --configuration Release --no-restore

    - name: publish EXE
      run: dotnet publish BluetoothLEExplorer/BluetoothLEExplorer/VirtualBT.csproj --configuration Release --output ./publish --no-restore

    - name: upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualBT-EXE
        path: ./publish
